services:
  identity-service:
    build: .
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: ""
      OPENKM_BASE_URL: http://openkm:8080/OpenKM
      OPENKM_USERNAME: okmAdmin
      OPENKM_PASSWORD: ""
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      - identity-network
    depends_on:
      - postgres

  #PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: identity_verification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - identity-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ""
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ""
      KC_HTTP_ENABLED: true
      KC_HTTPS_ENABLED: false
    ports:
      - "8090:8080"
    networks:
      - identity-network
    depends_on:
      - postgres
    command: start-dev

  # OpenKM
  openkm:
    image: openkm/openkm-ce
    volumes:
      - openkm_data:/opt/tomcat
    ports:
      - "8088:8080"
    networks:
      - identity-network

volumes:
  postgres_data:
  openkm_data:

networks:
  identity-network: